version: "2"

services:
  web:
    build: .
    container_name: proctest_node_server
    ports:
      - 80:5000
    environment:
      - URI=mongodb://mongo/proctest
      - HOST=mongo
    links:
      - mongo

  mongo:
    image: mongo
    container_name: proctest_mongo_server
    volumes:
      - /data/mongodb/proctest/db:/data/db
