version: "2"
services:
  web:
    build: .
    container_name: node_server
    ports:
      - 5000:5000
    links:
      - mongodb

  mongodb:
   image: mongo
   container_name: mongodb_server
   ports:
    - 27017:27017
   volumes:
    - /data/mongodb/db:/data/db
